### ISSUE TITLE
Preparing KITTI dataset

### ISSUE THREAD

**Issue by mwdotzom** [XiangMochu/MDEUncertainty#1]
Hi Mochu, thanks for your remarkable insight into the nature of MDE uncertainty!

I'd love to have a try of your implementation, but I didn't find the instruction for preparing KITTI in README. 
Is there a specific requirement of its data structure to be specified in `utils/kitti_data.py`?
Should I use the official source directly, or use some 3rd-party script like [this one](https://github.com/mattpoggi/mono-uncertainty/blob/master/prepare_kitti_data.sh)?

Thx! Haokun

**Comment by XiangMochu** [comment]
Hi Haokun, you can try using this script, but simply downloading KITTI Raw and the annotated depth maps (data_depth_annotated.zip) is gonna work. There are several things that might be helpful:

1. [this script](https://github.com/mattpoggi/mono-uncertainty/blob/master/prepare_kitti_data.sh) converts the raw image from png-s to jpg-s. It will make the image lose some details, and might harm the performance.
2. If you manually download the data_depth_annotated.zip, after unzipping it, merge the `train` and `val` folder, because Eigen split is different from this split.

Thanks for your interest in our work!

**Comment by mwdotzom** [comment]
Thanks for the help! For anyone's information, I traced down the references and found the _kitti eigen split_ download instructions here: [depth](https://github.com/cleinc/bts#prepare-kitti-official-ground-truth-depth-maps) and [raw images](https://github.com/cleinc/bts/tree/master/pytorch#kitti). After configuration and merging, my data directory now aligns with the code.
> 2\. If you manually download the data_depth_annotated.zip, after unzipping it, merge the `train` and `val` folder, because Eigen split is different from this split.


However, I met this exception on training:
```
missing kitti_data/img/2011_09_30/2011_09_30_drive_0020_sync/image_02/data/0000000282.jpg
missing kitti_data/img/2011_09_26/2011_09_26_drive_0014_sync/image_02/data/0000000062.jpg
...
```
the images are present, but their original downloaded format is png. The problem seems to be caused here:
https://github.com/XiangMochu/MDEUncertainty/blob/20485b9506577eac96356c18f4069122af85edbd/utils/kitti_data.py#L101

which is confusing as you mentioned they are not supposed to be converted to jpgs. Could you please clarify what I should do, shall I convert them all to jpgs or alter the code? Very much appreciated!

Haokun

**Comment by XiangMochu** [comment]
Oh so I actually used compressed jpg-s in this project, you can try commenting this line and use pngs, this might give you higher performance, but won't be too much.

**Comment by mwdotzom** [comment]
Got it, I commented out the two lines of this replacement, and the training works now, cheers!
